### PR TITLE
Add "Three Card Summon"

### PR DESCRIPTION
**Pull request by idk-what-to-name-here**
https://yugipedia.com/wiki/Three_Card_Summon
- [X] I am following the [contributing guidelines](https://github.com/ProjectIgnis/CardScripts/blob/master/CONTRIBUTING.md).
- [X] I am making the [changes to modernize the scripts](https://github.com/ProjectIgnis/CardScripts/blob/master/MODERNIZING.md).

**New card checklist**

- [X] I have submitted a corresponding database entry for [BabelCDB](https://github.com/ProjectIgnis/BabelCDB/blob/master/README.md) according to its guidelines. Link to the pull request: _https://github.com/larry126/BabelCDB/pull/121_
- [X] This card is not marked with a reason to not be added in the unofficial card tracker in `#card-scripting-101`.
Supervising staff member(s): _larry126_

### CODE REVIEW

**Comment by idk-what-to-name-here** [comment]
updated he script

**Comment by idk-what-to-name-here** [comment]
if my cdb files are broken, probably because i made those on my phone

**Comment by idk-what-to-name-here** [comment]
because my coumpter is broken

**Comment by larry126** [comment]
Just done cleaning up the script, here are a few notable points:
1. The indentation in what was the cost function, which I've turned into target for this effect specifically as it's relevant to its activation legality, was a mess.
2. If an effect that would select a monster(s) during operation (in the yugioh term, during the resolution) to Summon, you often need to check whether there are enough zones on the field first, and if there aren't, you do not proceed to the monster selection.
3. Back to the target function, good job on transforming it into using `aux.SelectUnselectGroup`, just a few small points of improvement/correction:
- It is possible to reveal 3 monsters in your hand, with 2 of them being unsummonable (for example, Spirit Monsters). Hence you do not need to filter out monsters that cannot be Special Summoned at the start, instead, check whether 1 of the 3 revealed monsters is Summonable inside `aux.SelectUnselectGroup`.
- `aux.SelectUnselectGroup` is actually a rather heavy function (as in it could tank the program significantly, albeit in this effect it probably wouldn't), so as a habit in general, when probable do not use it in the target check or cost check so it would not get executed upon every open gamestate. This is why I kinda reverted the target check to the previous edition of the script.
- I also used `Duel.SetTargetCard` to keep track of the revealed card for 2 reasons. Firstly, something might happen to the revealed cards before the effect resolves. (e.g. banish, discard, etc.) Therefore, store them as target cards would automatically filter out any monsters that are no longer considered the revealed ones. Secondly, this is often a preferred method to keep track of cards for an activated effect over Label Object, because Label Object will persist even after the effect has resolved, but by then the group of cards has become irrelevant to the gamestate.

This sums up the edits I've done to the script. I'll merge the PR later once I've got the cdb file ready.

**Comment by idk-what-to-name-here** [comment]
btw this is the id for the cdb: 511027765

**Comment by idk-what-to-name-here** [comment]
an string 1 is Activate

**Comment by larry126** [comment]
1 minor thing I forgot to mention, so far all 3 cards of yours had the incorrect Japanese name at the top of the script.

**Pull request merged**
