### PR TITLE
Add "Revibubble"

### PR DESCRIPTION
**Pull request by botist**
https://yugipedia.com/wiki/Revibubble

- [x] I am following the [contributing guidelines](https://github.com/ProjectIgnis/CardScripts/blob/master/CONTRIBUTING.md).

**New card checklist**

- [x] I have submitted a corresponding database entry for [BabelCDB](https://github.com/ProjectIgnis/BabelCDB/blob/master/README.md) according to its guidelines. Link to the pull request: https://github.com/larry126/BabelCDB/pull/48
- [x] This card is not marked with a reason to not be added in the unofficial card tracker in `#card-scripting-101`.
Supervising staff member(s): @larry126

### CODE REVIEW

**Comment by Rundas01** [comment]
For my understanding "select" doesn't mean "target". Moreover, "e" and "tp" in your filter are obsolete.

**Comment by botist** [comment]
https://yugipedia.com/wiki/Select
are you sure?

**Comment by larry126** [comment]
Action Card, and implemented

**Comment by botist** [comment]
oh my god its an action card, rofl

**Pull request closed without merging**
