### PR TITLE
Add "G.O.D.-Eyes Phantom Dragon (again)

### PR DESCRIPTION
**Pull request by 42Rundas**
Sorry for opening this again, but I had to delete my fork for this repo.
I needed to figure out how not to include commits from this pull request into the other one I opened today.
Again, sorry for any inconveniences

### CODE REVIEW

**Comment by kevinlul** [comment]
Old PR #227

**Comment by 42Rundas** [comment]
Neither of the 2 said anything about what the ID should be. I'll ask senpai.

**Comment by 42Rundas** [comment]
@kevinlul ID is changed to a proper value

**Comment by 42Rundas** [comment]
@pyrQ Would you please be so kind to review this PR.
It seems that even if a review is requested, Kevin doesn't want to.

**Comment by pyrQ** [comment]
We will need to examine the ARC-V manga to verify that the effects are the correct ones, so it'll probably have to wait until Larry or CC have the time to do that.

**Comment by 42Rundas** [comment]
Ok, I just scripted the effects which are listed on the pedia entry xD

**Pull request closed without merging**
