### PR TITLE
Add "Acorno (Anime)"

### PR DESCRIPTION
**Pull request by 42Rundas**
https://yugipedia.com/wiki/Acorno_(anime)

### CODE REVIEW

**Comment by larry126** [comment]
Cost should be in cost.
Simple solution: copy Defcon Bird and then make changes based on that.

**Comment by 42Rundas** [comment]
@larry126 this card doesn't have cost since there is no ";", but rather a ":"

**Comment by larry126** [comment]
Looks good, although because the "send to grave" part is now confirmed effect (sorry about the message above, just ignore it), you would need CATEGORY_TOGRAVE and respective SetOperationInfo in SetTarget. I'll do it in a moment to demonstrate.

**Comment by 42Rundas** [comment]
well, I was too quick with the submission xD

**Pull request merged**
