### PR TITLE
Add "Mirror Imagine Reflector 1,2 and 3"

### PR DESCRIPTION
**Pull request by Beetletop**
https://yugipedia.com/wiki/Mirror_Imagine_Reflector_1
https://yugipedia.com/wiki/Mirror_Imagine_Reflector_2
https://yugipedia.com/wiki/Mirror_Imagine_Reflector_3

- [X] I am following the [contributing guidelines](https://github.com/ProjectIgnis/CardScripts/blob/master/CONTRIBUTING.md).

**New card checklist**

- [X] I have submitted a corresponding database entry for [BabelCDB](https://github.com/ProjectIgnis/BabelCDB/blob/master/README.md) according to its guidelines. Link to the pull request: _https://github.com/larry126/BabelCDB/pull/90_
- [X] This card is not marked with a reason to not be added in the unofficial card tracker in `#card-scripting-101`.
Supervising staff member(s): _@larry126_

### CODE REVIEW

**Comment by Beetletop** [comment]
I actually have alot of hope for all these 3 cards. Mirror imagines had their effects,pendulum scales,types and attributes assumed (types and attributes were assumed most likely from what they looked like). So i found the odds of 2 and 3's defense being assumed the same as 1 pretty high. They share the same names, same appearances, very similar effects with tiny changes made. If it really is impossible to assume, i will delete 2 and 3's scripts and remove most of 1's effects. But i believe Mirror Imagine Reflector 1 %100 should make it in.

**Comment by Beetletop** [comment]
Also sorry for sending 3 PR's at once, i didn't think deleting fork would close all those pull requests

**Comment by larry126** [comment]
DEF cannot be assumed in this case after staff discussion

**Comment by Beetletop** [comment]
> DEF cannot be assumed in this case after staff discussion

But why...? Type/Attribute were assumed with no evidence besides i doubt mirror imagines will get printed irl so it wouldnt clash either

**Pull request closed without merging**
