### PR TITLE
Add "Mischief of the Time Goddess (Anime)"

### PR DESCRIPTION
**Pull request by Rundas01**
https://yugipedia.com/wiki/Mischief_of_the_Time_Goddess_(anime)

One small thing remains: The text says "skip 1 turn" which sounds to me that I can only use the card during the opponents turn since if I would use it during my turn, then it would skip more than 1 entire turn. So technically the card should be activatable from the BP onwards. (But I made it activatable during the entire turn). Feedback on that is appreciated.

@larry126

### CODE REVIEW

**Comment by kevinlul** [comment]
In the future please do not erase the pull request template checklist as it codifies some of the contributing process. FYI Larry is a bit busy as of late.

**Comment by 42Rundas** [comment]
Ok, thanks for the info. I thought it was for new contributors who are not aware of the general procedure. Will keep that in mind.

**Comment by larry126** [comment]
Here's my input:
Considering the phrase "1 turn" could be ambiguous in DM anime, I would focus on the action of "skipping turn" instead. Therefore the card would be more or less identical to its OCG/TCG counterpart.

**Comment by 42Rundas** [comment]
> Here's my input:
> Considering the phrase "1 turn" could be ambiguous in DM anime, I would focus on the action of "skipping turn" instead. Therefore the card would be more or less identical to its OCG/TCG counterpart.

so it's only activatable in the BP?

**Comment by larry126** [comment]
And no BP restriction, as it was shown in Gx

**Comment by larry126** [comment]
It's still not changed the way I described

**Comment by Rundas01** [comment]
@larry126 if the newest change is not to your liking, I'm afraid that I don't know what you mean with "no BP restriction" xD

**Pull request closed without merging**
