### PR TITLE
Add "Pegasus Ultimate Challenge"

### PR DESCRIPTION
**Pull request by AlphaKretin**
This special Duel Mode was created for Percy 2 years ago and never added. It seems like a waste to not include it here, however, it needs to be tested for functionality in the new simulator, both in general and each challenge it can apply. 

Things to be tested:
- [x] Basic operation (Duel applying on startup, issuing challenges)
- [ ] 1: All players reveal the top card of their deck. You may play that card immediately, starting with the turn player.
- [x] 2: Both players play with their hands revealed.
- [x] 3: Destroy all monsters with five or more stars.
- [x] 4: Everyone discard a random card from their hand.
- [x] 5: Everyone stop and introduce yourself to the person sitting on your right.
- [x] 6: Lose 500 LP for each Spell and Trap Card you control.
- [x] 7: Shuffle your hand into your deck and then draw that many cards.
- [x] 8: Swap LP with your opponent.
- [x] 9: Destroy all monsters with 1500 or less ATK.
- [x] 10: If you had a card destroyed this turn, you may destroy one of your opponent's cards.
- [x] 11: Players cannot activate Spell Cards. (They could activate their effects.)
- [x] 12: Remove all cards in all graveyard from the game.
- [x] 13: Switch the ATK and DEF of all monsters on the field.
- [x] 14: Turn your deck over and then draw from the new top of the deck.
- [x] 15: You cannot attack unless you say "Yu-Gi-Oh!"
- [x] 16: All monsters become Normal Monsters with no effects.
- [x] 17: Destroy all cards on the field.
- [x] 18: Destroy all monsters.
- [x] 19: Destroy all Spell and Trap Cards.
- [x] 20: Destroy all face-up Xyz Monsters.
- [x] 21: Discard your hand and then draw that many cards.
- [x] 22: Everyone draw the bottom card of their Deck.
- [x] 23: If you have less LP than your opponent, Special Summon one monster from your hand to the field, ignore all Summoning conditions.
- [x] 24: Players cannot activate Trap Cards. (They could activate their effects.)
- [x] 25: Shuffle your Graveyard into your Deck and then put the top 15 cards of your Deck into the Graveyard.
- [x] 26: Destroy all Continuous Spell and Trap Cards.
- [x] 27: Destroy all monsters with 1500 or more ATK.
- [x] 28: Destroy all monsters with 4 or less Levels.
- [x] 29: No monsters can be face-down, flip all face-down monsters to face up and their flip effects are negated.
- [ ] 30: Swap monsters with your opponent. All of them.
- [x] 31: Turn all monsters face-down. They cannot be flipped up this turn.
- [x] 32: You can only activate cards on your turn.
- [x] 33: All duelists must discard a card at random.
- [x] 34: For three turns, all monsters have "Jam" added to the ends of their names. When a "Jam" monster is destroyed, you can Special Summon it back to the field in Defense Position.
- [x] 35: For three turns, duelists can activate trap cards from their hands.
- [ ] 36: By paying 1000 Life Points per monster, players may smite any number of their opponent's monsters and send them to the Graveyard.
- [ ] 37: Necrovalley is in effect for three turns. Cards cannot leave the Graveyard for 3 turns.
- [ ] 38: Choose a monster, a spell, and a trap card from your Graveyard and set them all onto your field.
- [x] 39: Each duelist must search his or her deck for any card, add it to their hand, and shuffle their deck afterward.
- [ ] 40: All old rules become no longer in effect, and all players reveal their hands and face-down cards to their opponents.
- [ ] 41: Choose a card in your opponent's graveyard and set it to your side of the field.
- [x] 42: Each duelist may draw up to two cards, but loses 1000 Life Points for each card he or she chooses to draw. The turn player decides how many cards to draw first.
- [x] 43: You can only play monsters with an ATK of 1600 or higher.

### CODE REVIEW

**Comment by AlphaKretin** [comment]
Cybercatman has suggested using a Duel.Hint of a card image which shows Pegasus or Marik as appropriate to spice things up at announcements. I like this idea, but I'll wait until I'm sure everything important works properly

**Comment by ClementLouis** [comment]
challenge 34 seem to work, but an hint that a monster is treated like a "Jam" monster would be good

**Comment by AlphaKretin** [comment]
I don't know why I'm looking at this issue at 1 AM when I'm not actively working on it, but I recall a discussion where it was revealed that the issue with summoning Link Spider in Challenge 16 was that their effects were being disabled even in the Extra Deck, even the Link Summon procedure (other procedures are correctly not negatable). I assume this would be an issue that should be fixed in the proc.

**Comment by AlphaKretin** [comment]
With the link procedure being updated to not be negatable, Challenge 16 now works

**Comment by DyXel** [comment]
Closing as this is stale.

**Pull request closed without merging**
