### PR TITLE
Add "Speedroid Red-Eyed Dice (Anime)"

### PR DESCRIPTION
**Pull request by idk-what-to-name-here**
https://yugipedia.com/wiki/Speedroid_Red-Eyed_Dice_(anime)
- [X] I am following the [contributing guidelines](https://github.com/ProjectIgnis/CardScripts/blob/master/CONTRIBUTING.md).
- [X] I am making the [changes to modernize the scripts](https://github.com/ProjectIgnis/CardScripts/blob/master/MODERNIZING.md).

**New card checklist**

- [X] I have submitted a corresponding database entry for [BabelCDB](https://github.com/ProjectIgnis/BabelCDB/blob/master/README.md) according to its guidelines. Link to the pull request: _https://github.com/larry126/BabelCDB/pull/119_
- [X] This card is not marked with a reason to not be added in the unofficial card tracker in `#card-scripting-101`.
Supervising staff member(s): _larry126_

### CODE REVIEW

**Comment by idk-what-to-name-here** [comment]
Yugipedia was wrong when you read the proxy doesnt say "Normal Summoned" instead it says "Summoned" meaning if it was Normal, Special or, Filp Summoned it will gain the change Level Effect.

**Comment by idk-what-to-name-here** [comment]
Also the Different Between Anime and Tcg version of "Speedroid Red-Eyed Dice" that in the Tcg Version of "Speedroid Red-Eyed Dice" it targets an "Speedroid" Monster, except "Speedroid Red-Eyed Dice" and change its Level from 1 to 6 Meanwhile in the Anime Version of "Speedroid Red-Eyed Dice" it Targets 1 other Level 1 Monster you control and change that monster level from 2 to 6.

**Comment by pyrQ** [comment]
> Yugipedia was wrong when you read the proxy doesnt say "Normal Summoned" instead it says "Summoned" meaning if it was Normal, Special or, Filp Summoned it will gain the change Level Effect.

Yugipedia is right, the card says `召喚` which directly translates to `Summon`, but that is the term used for `Normal Summon` in the OCG (`通常召喚` for `Normal Summon/Set`). If an effect can be used on any kind of summon (Normal, Flip, and Special) then they are each individually listed in the card text.

For examples, for an effect that activates upon any kind of summon you can look at the JP text of `Satellarknight Deneb`, and for one that activates only on Normal Summon you can look at the JP text of `Junk Synchron`.

**Comment by idk-what-to-name-here** [comment]
oh then lets me edit my script real quick

**Pull request merged**
