### PR TITLE
Add "Parallel World Fusion (Manga)"

### PR DESCRIPTION
**Pull request by Dakota407**
https://yugipedia.com/wiki/Parallel_World_Fusion_(manga)

- [X] I am following the [contributing guidelines](https://github.com/ProjectIgnis/CardScripts/blob/master/CONTRIBUTING.md).
- [X] I am making the [changes to modernize the scripts](https://github.com/ProjectIgnis/CardScripts/blob/master/MODERNIZING.md).

**New card checklist**

- [X] I have submitted a corresponding database entry for [BabelCDB](https://github.com/ProjectIgnis/BabelCDB/blob/master/README.md) according to its guidelines. Link to the pull request: https://github.com/larry126/BabelCDB/pull/147#issue-1879232265
- [X] This card is not marked with a reason to not be added in the unofficial card tracker in `#card-scripting-101`.
Supervising staff member(s): larry126

### CODE REVIEW

**Comment by larry126** [comment]
Why is this card in the 5110024xx range?

**Comment by Dakota407** [comment]
I copied the range of existing unofficial cards and increased the ID by 1 until I found a slot that wasn’t occupied. Honestly, it was surprising that 511002399 and 511002401 were taken, but not 511002400! Did I mess that one up this time? Sent from Mail for Windows From: Larry126Sent: Monday, September 4, 2023 12:05 AMTo: ProjectIgnis/CardScriptsCc: Dakota407; AuthorSubject: Re: [ProjectIgnis/CardScripts] Add "Parallel World Fusion (Manga)" (PR #1090) Why is this card in the 5110024xx range?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Dakota407** [comment]
I do apologize, I’m not exactly well versed in this. I thought I removed
the restriction too! I was able to summon Dark Flare Knight and Flame
Wingman on the same turn with it, so I’m confused. Regardless, I clearly
made a mistake, and I apologize for taking up your time. I really do
appreciate what you do for the Anime/Manga community here, and I respect
you a lot. Have a nice day! :)

**Comment by larry126** [comment]
For the record, I didn't really blame you or anything, but you should definitely come to GitHub web and see how the previous message looks like for everyone else xd

**Pull request closed without merging**
