### PR TITLE
Add "Vain Betrayer (anime)

### PR DESCRIPTION
**Pull request by 42Rundas**
https://yugipedia.com/wiki/Vain_Betrayer_(anime)

Maybe the ID is correctly chosen for once xD

### CODE REVIEW

**Comment by larry126** [comment]
A few improvements or fixes:
1. The JP name is wrong
2. Some indentation errors
3. Because you send cards from your opponent's Deck, which isn't a knowledge available to you, you can activate the effect without needing to check whether your opponent has a "V" card. Instead, you should check whether you opponent could send a card from their Deck to the Graveyard.

**Comment by larry126** [comment]
And yes, the ID is in a staff member's range, need changing.

**Comment by 42Rundas** [comment]
Changed ID and the JP name
@larry126

**Comment by 42Rundas** [comment]
made the changes (hopefully to your liking this time xD)
@larry126

**Pull request merged**
