### PR TITLE
Small Fix for "Marksman Heiji Type 0"

### PR DESCRIPTION
**Pull request by Rundas01**
There were occasions where materials which originate from the Extra Deck couldn't be summoned with e2, although they have been properly summoned b4.
- [x] I am following the [contributing guidelines](https://github.com/ProjectIgnis/CardScripts/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by larry126** [comment]
Can you describe the exact scenario this bug would occur?

**Comment by Rundas01** [comment]
> Can you describe the exact scenario this bug would occur?

Well, this PR was opened in March. Which means I have no idea anymore what the scenario was exactly. I'll come back to this, once I encounter the problem again.

**Comment by pyrQ** [comment]
Removing the `c:GetReasonCard()==sync` would make them Special Summonable even if they leave the GY and are used as Synchro Materials again, I reckon, so that would be wrong regardless.

**Comment by Rundas01** [comment]
> Removing the `c:GetReasonCard()==sync` would make them Special Summonable even if they leave the GY and are used as Synchro Materials again, I reckon, so that would be wrong regardless.

that is true

**Comment by larry126** [comment]
Sorry, for now I cannot identify the necessity of this change
Feel free to PR again once you've replicated the error and figured out the cause of the issue

**Pull request closed without merging**
