### PR TITLE
Update for "Chaos Hundred Universe"

### PR DESCRIPTION
**Pull request by 42Rundas**
The old script was outdated and is now updated with a globalcheck and the proper hint timings.

### CODE REVIEW

**Comment by larry126** [comment]
I don't quite understand the needs of using global functions as "that were destroyed under your control this turn" could be checked using several functions from my understandings.
Additionally, the way you keep them in a group is possible to cause errors, for example if a Number C101 that was destroyed under your control this turn got banished by Soul Release and immediately returned by PSY-Framelord Omega, it is no longer considered a monster destroyed under your control but your group will still keep it.
Lastly, it is currently working in Edopro, what was fixed in this PR?

**Comment by 42Rundas** [comment]
@larry126 I was talking to senpai about this card, since I thought it was buggy.
You needed to hold "A" to activate during the opponent's turn because no hint timing was in the script. After senpai looked over the script he said, the card was poorly scripted and would use such a globalcheck instead. 
I can either deal with the problem you mentioned above, or upload a the original script for universe with the proper hint timings.

**Comment by 42Rundas** [comment]
I decided to add the hint timings for simplifying the usage of the card during the opponent's turn in the original script. Also I shortened the operation a bit such that only one loop of negating effects is necessary.

**Comment by larry126** [comment]
I see, I will chat with senpai later about the optimized method to implement this card.
I do agree with adding hint timing though, it is good for player experience.

**Pull request closed without merging**
