### PR TITLE
Add "Marincess Decision"

### PR DESCRIPTION
**Pull request by TheRazgriz**
Script for Marincess Decision

https://yugipedia.com/wiki/Marincess_Decision

@ClementLouis 
@pyrQ 
@larry126

### CODE REVIEW

**Comment by larry126** [comment]
I'll take care of this PR.

**Comment by larry126** [comment]
You should put the script in /unofficial, not in the root directory

**Comment by larry126** [comment]
```lua
function s.costfilter(c)
    return c:IsSetCard(0x12b) and c:IsAbleToRemoveAsCost() and aux.SpElimFilter(c,true)
end
function s.linkcost(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return Duel.IsExistingMatchingCard(s.costfilter,tp,LOCATION_MZONE+LOCATION_GRAVE,0,1,nil) end
    Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
    local g=Duel.SelectMatchingCard(tp,s.costfilter,tp,LOCATION_MZONE+LOCATION_GRAVE,0,1,1,nil)
    Duel.Remove(g,POS_FACEUP,REASON_COST)
end

**Comment by larry126** [comment]
After investigations, it seems that the current Link Procedure still doesn't support checking a face-down monster as Link Material, hence the first effect of Marincess Decision can't be properly implemented (you should only target a facedown monster that could be used for a Link Summon once flipped up).

Also, there is an error in graveyard banish cost check, the following is the correct version:
```lua
function s.costfilter(c)
    return c:IsSetCard(0x12b) and c:IsAbleToRemoveAsCost() and aux.SpElimFilter(c,true)
end
function s.linkcost(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return Duel.IsExistingMatchingCard(s.costfilter,tp,LOCATION_MZONE+LOCATION_GRAVE,0,1,nil) end
    Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
    local g=Duel.SelectMatchingCard(tp,s.costfilter,tp,LOCATION_MZONE+LOCATION_GRAVE,0,1,1,nil)
    Duel.Remove(g,POS_FACEUP,REASON_COST)
end
```
You need to make the location _LOCATION_MZONE+LOCATION_GRAVE_ for _aux.SpElimFilter(c,true)_, the handling of Spirit Elimination.

Other than that, the script quality is good, 100% passable. Keep on the good job!

**Comment by larry126** [comment]
If the problem is ever fixed, feel free to PR again. Same goes to Rousing Hydradrive, sorry I missed the message.

**Comment by TheRazgriz** [comment]
I suppose I'm confused (I didn't realize about the SpElimfilter, and fixed it), because I tried testing the script with Centerfrog (since it doesn't allow itself to be used as Link Material), and it seemed to disallow as it should. Unless that's the actual issue?

Just seems like I've been shot down repeatedly for trying to help out, and wonder if I should even continue trying.

**Comment by TheRazgriz** [comment]
And by add a "IsCanBeLinkMaterial" check to my deffilter, it seems to not allow facedown centerfrog to be targeted.

**Comment by TheRazgriz** [comment]
Ah wait, I see the issue. Never mind. 

Sorry, just seems like I've managed to try scripting cards that seem to have something that can't be used.

**Comment by pyrQ** [comment]
Most cards (especially VRAINS cards) that aren't already in the game are because they cannot be implemented.

**Comment by TheRazgriz** [comment]
I get that, but it just feels like the wind just flops out of my sails when I work hard on a script, only to find that something prevents its implementation.

Nothing against the devs, just sucks is all.

**Pull request closed without merging**
