### PR TITLE
Fix category assignments on various cards with choice effects

### PR DESCRIPTION
**Pull request by BarnacleYoghurt**
Some cards with effects that let the player choose between one of several effects on activation ("activate 1 of these effects;") have their category set to a static value, usually all applicable categories. This means that regardless of choice, the activated effect also has the categories of the other options, and therefore e.g. Ash Blossom can be chained even if the player did not choose to use the effect that would actually fulfill its conditions.

Other cards, such as Triple Tactics Talent, use a more correct approach where the category is updated once the player makes their selection each time the effect is activated. I have updated all scripts I could find with the above issue to also work that way, specifically:
* **Cyber Repair Plant** and **D/D Savant Kepler** suffered from the noted incorrect interaction with Ash Blossom, since CATEGORY_SEARCH was among their misreported categories.
* **Don Zaloog**, the four **Dark Scorpion** monsters, **Dinomist Rex**, **Cyber Raider**, **Yamorimori**, **Majestic Absorption**, **Enemy Controller**, **Heavy Forward**, **Six Strike - Thunder Blast**, **Graydle Combat**, and **Kunai with Chain** also had static category values, but I am not aware with any interaction where they would actually have mattered; fixing these is just futureproofing.
* **Outstanding Dog Mary** and **Solfachord Elegance** already had the correct dynamic category handling, but didn't assign a value for every possible choice. Not sure if the category change would actually persist between two activations, but just to be safe I have also updated these.

- [x] I am following the [contributing guidelines](https://github.com/ProjectIgnis/CardScripts/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by NaimSantos — APPROVED** [review]
This looks fine, but since it will introduce new scripts to the deltautopia repository (because someone the files changed in the PR are not there yet), it would be good if you could also [follow the suggestions to modernize](https://github.com/ProjectIgnis/CardScripts/blob/master/MODERNIZING.md) the scripts.

**Comment by BarnacleYoghurt** [comment]
Didn't know about that, but sure, can do. Just to be sure, that means all of them except Yamorimori (*c51474037*) Majestic Absorption (*c63144961*), Heavy Forward (*c34721681*), Outstanding Dog Mary (*c71583486*), and Solfachord Elegance (*c27870337*), right?

Also, while we're at it, I would guess Kunai with Chain doesn't actually need to have two distinct scripts for its two artworks, probably only the *c37390589* one since that's the main code. Should I just ignore the other one or do something to actively remove it?

**Comment by NaimSantos** [comment]
Ideally, _all_ the scripts that are being submitted via pull request should also be edited to include the changes listed in the modernizing file. I just mentioned that this will introduce new files to the deltapuppet repository because those new files for sure don't follow all the suggestions.

For example, for a quick verification:
- c63144961: could have the listed series hexadecimal value replaced by its constant name, could use Duel.SelectEffect instead of those 7 Duel.SelectOption calls. It can also have the `+` operators replaced by `|` in the resets.
- c34721681: could have the listed series hexadecimal value replaced by its constant name.

Kunai with Chain's second art's script can be removed, but that won't do anything for the users because they already have the script in the main script folder. Deleting it here won't cause it to be removed there.

**Comment by BarnacleYoghurt** [comment]
Alright, in that case I'll try to go over all of them. And if removing the extra script isn't a problem, I'll do that just for the sake of maybe saving future contributors the question "do I need to change both".

**Comment by BarnacleYoghurt** [comment]
Thanks for the polish. I was planning on one last big round of checking to make sure I didn't forget/mess up anything, should I still do that or is it better if I keep my hands off at this point?

Also, how is the cdb going to get the new strings for the descriptions added with modernization updates? Doesn't look like I can just go and open a PR over there.

**Comment by pyrQ** [comment]
> Thanks for the polish. I was planning on one last big round of checking to make sure I didn't forget/mess up anything, should I still do that or is it better if I keep my hands off at this point?

Well, if you want to take a look and see an issue then feel free to fix it but try to limit it to actual issues (e.g. no style changes that I'll just change back, kind of a waste of time and energy). There are also a few cards that I didn't go through yet, was busy with other things so it got pushed back a bit, will continue with those when I can.
> Also, how is the cdb going to get the new strings for the descriptions added with modernization updates? Doesn't look like I can just go and open a PR over there.

I'll update the relevant cdb entries accordingly when this PR gets merged.

**Review by pyrQ — APPROVED** [review]

**Comment by pyrQ** [comment]
Related cdb updates here https://github.com/ProjectIgnis/BabelCDB/commit/2aaf1ec363141f182fc8b4098bcdc5553e1eaa63

**Pull request merged**
