### PR TITLE
Add contributing guidelines [ci skip]

### PR DESCRIPTION
**Pull request by kevinlul**

### CODE REVIEW

**Comment by kevinlul** [comment]
Open for discussion and amendments from staff.

**Comment by NaimSantos** [comment]
Limit adding new cards only to Project Ignis's Card Scripters for official cards, as we have our own workflow for that.
For non-official cards, a pull request with the card script, a link to Yugipedia's page of that card, showing that the script matches its text and then request review from one of the Scripters that work with that area. If the reviewer approves the PR, the author must provide cdb and proxy on Discord to us, so no card is added without them.

**Comment by larry126** [comment]
I pretty much agree everything above. Just 1 minor thing I wish to raise as Naim's suggestion didn't quite clarify it. For non-staff member submitting unofficial contents, should we restrict to 1 per PR or they could submit as much as possible as long as providing the required information like Pedia link, etc.

**Comment by ahtelel** [comment]
+ The things I can agree with:
- No one besides the team can edit the cdbs' contents, as we will be the ones to judge whether information is correct or not to put in the game
- If anyone wants to open an issue, they can go to Discord instead, which means we need to close the ability to make issues in any repo
- Pulls for both official and unofficial cards can be made, but the best way to demonstrate that the pull work will be needed, e.g. a short video captured by OBS, or if the details are enough to be contained in images, images. Videos will be the preferred format of proof
+ Sometimes, bugs can be lost in the help channels of Discord. I suggest that there be some way to enable enthusiastic helpers in the help channels to make a record of bugs that they have verified to exist. The structure of Discord seems to make this very hard, however, as (here are some things I have thought of)
- giving the enthusiasts a role is tantamount to making them official helpers, in which individual cases, some might not agree with
- giving the ability to pin messages for everyone will result in a total panic
- giving the ability to see and type in a separate channel is somewhat the same as giving roles

**Comment by larry126** [comment]
Right, my only query is solved and there is nothing I disagree with. I also agree adding whatever we discussed and agreed here in readme in a constructive way.

**Comment by kevinlul** [comment]
> 
> 
> I agree with adding Larry's suggestion to limit the number of Pull Requests to 1 at time to non-regular contributors, so we're not overloaded with those. Also, the README file's lines 14 to 17 are too generic. I suggest adding what was proposed here to that section

The main README tells you to read CONTRIBUTING. I didn't want to paste the same contents in both files to avoid clogging the main README and making it really long. Because I reiterate to "please speak with a member of staff in `#card-scripting-101` first", I feel this addresses the single-PR concern for random contributions, as that can probably be handled on a case-by-case basis with that rule.

**Pull request merged**
